version: 2.1

exitsuccess: &exitsuccess
    name: Exit on Successful Build
    command: exit 0

orbs:
  # https://circleci.com/orbs/registry/orb/circleci/docker-publish
  docker-publish: circleci/docker-publish@0.1.2
workflows:

  # This workflow will be run on all branches but master (to test)
  docker_with_lifecycle:
    jobs:
      - docker-publish/publish:
          image: pydicom/dicom-ocr-cleaner
          dockerfile: ocr/Dockerfile
          path: ocr
          after_build:
            - run: *exitsuccess
          filters:
            branches:
              ignore: master

      - docker-publish/publish:
          image: pydicom/dicom-header-cleaner
          dockerfile: header/Dockerfile
          path: header
          after_build:
            - run: *exitsuccess
          filters:
            branches:
              ignore: master

  # This workflow will deploy images on merge to master only
  build_and_publish_docker_images:
    jobs:
      - docker-publish/publish:
          image: pydicom/dicom-ocr-cleaner
          dockerfile: ocr/Dockerfile
          path: ocr
          filters:
            branches:
              only: master
      - docker-publish/publish:
          image: pydicom/dicom-ocr-cleaner
          dockerfile: ocr/Dockerfile
          tag: latest
          path: ocr
          filters:
            branches:
              only: master
      - docker-publish/publish:
          image: pydicom/dicom-header-cleaner
          dockerfile: header/Dockerfile
          path: header
          filters:
            branches:
              only: master
      - docker-publish/publish:
          image: pydicom/dicom-header-cleaner
          tag: latest
          dockerfile: header/Dockerfile
          path: header
          filters:
            branches:
              only: master
